
// an array of objects with fields label and value 
export const destination = [
 {label: "Los Angeles", value: "los angeles"},
 {label: "Santa Monica", value: "santa monica"},
 {label: "Beverly Hills", value: "baverly hills"},
 {label: "Pasadena", value: "pasadena"},
 {label: "Gledale", value: "glendale"},
 {label: "Burbank", value: "burbank"},
 {label: "West Hollywood", value: "west hollywood"},
 {label: "Culver City", value: "culver city"},
 {label: "Inglewood", value: "inglewood"},
 {label: "Long Beach", value: "long beach"},
 {label: "Malibu", value: "malibu"},
 {label: "Anaheim", value: "Anaheim"}, 
 {label: "Huntington Beach", value: "huntington beach"},
 {label: "Irvine", value: "irvine"},
 {label: "Santa Ana", value: "santa ana"},
 {label: "Torrance", value: "torrance"},
 {label: "Rendondo Beach", value: "rendondo beach"},
 {label: "Manhattan Beach", value: "manhattan beach"},
 {label: "San Gabriel", value: "san gabriel"}, 
 {label: "Pomona", value: "pomona"},
 {label: "Fullerton", value: "fullerton"},
 {label: "El segundo", value: "el segundo"},
 {label: "San Fernando", value: "san fernando"},
 {label: "La Mirada", value: "la mirada"},
 {label: "Monterey Park", value: "monterey park"},
 {label: "Norwalk", value: "norwalk"}
];